language: erlang

services:
    - mysql

before_script:
    - "./travis-ci-setup -h127.0.0.1 -utravis"
    - make

script: "make test"

otp_release:
   - 19.1
   - 19.0
   - 18.0
   - 17.5
   - R16B03-1
   - R16B
   - R15B03
   - R14B04
